######################################################################
# Automatically generated by qmake (3.0) Wed Oct 28 14:04:15 2015
######################################################################
QT       += core gui widgets
TEMPLATE = app
TARGET = non_gui
INCLUDEPATH += .

# Input
SOURCES += hello_world.cpp
